apiVersion: v1
kind: Service
metadata:
  name: kafka-ext
  namespace: nt-practice-kafka
spec:
  type: NodePort
  selector:
    app: kafka-app
  ports:
    - name: external
      port: 9094
      targetPort: 9094
      nodePort: 30094