apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-claim-0
  namespace: nt-practice-kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: kafka-app